// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFrontForCall() {
  return window['go']['main']['App']['BringToFrontForCall']();
}

export function CallNotifRespond(arg1) {
  return window['go']['main']['App']['CallNotifRespond'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadAndUpdate() {
  return window['go']['main']['App']['DownloadAndUpdate']();
}

export function FetchPublicIp() {
  return window['go']['main']['App']['FetchPublicIp']();
}

export function FileExistsInDownloads(arg1) {
  return window['go']['main']['App']['FileExistsInDownloads'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAppVersionInfo() {
  return window['go']['main']['App']['GetAppVersionInfo']();
}

export function GetAppliedProxy() {
  return window['go']['main']['App']['GetAppliedProxy']();
}

export function GetCloseToTray() {
  return window['go']['main']['App']['GetCloseToTray']();
}

export function GetDownloadPath(arg1) {
  return window['go']['main']['App']['GetDownloadPath'](arg1);
}

export function GetGeoLocation() {
  return window['go']['main']['App']['GetGeoLocation']();
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function GetToastData() {
  return window['go']['main']['App']['GetToastData']();
}

export function GetToastPosition() {
  return window['go']['main']['App']['GetToastPosition']();
}

export function HideCallNotif() {
  return window['go']['main']['App']['HideCallNotif']();
}

export function IsWindowFocused() {
  return window['go']['main']['App']['IsWindowFocused']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function PlayNotificationSound() {
  return window['go']['main']['App']['PlayNotificationSound']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestoreNormalWindow() {
  return window['go']['main']['App']['RestoreNormalWindow']();
}

export function SaveFileFromURL(arg1, arg2) {
  return window['go']['main']['App']['SaveFileFromURL'](arg1, arg2);
}

export function SaveProxyConfig(arg1) {
  return window['go']['main']['App']['SaveProxyConfig'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function SetToastPosition(arg1) {
  return window['go']['main']['App']['SetToastPosition'](arg1);
}

export function ShowCallNotif(arg1) {
  return window['go']['main']['App']['ShowCallNotif'](arg1);
}

export function ShowCustomToast(arg1, arg2) {
  return window['go']['main']['App']['ShowCustomToast'](arg1, arg2);
}

export function ShowInExplorer(arg1) {
  return window['go']['main']['App']['ShowInExplorer'](arg1);
}

export function ShowOSNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowOSNotification'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
