// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BringToFrontForCall():Promise<boolean>;

export function CallNotifRespond(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function DownloadAndUpdate():Promise<Record<string, any>>;

export function FetchPublicIp():Promise<Record<string, any>>;

export function FileExistsInDownloads(arg1:string):Promise<boolean>;

export function GetAppVersion():Promise<string>;

export function GetAppVersionInfo():Promise<string>;

export function GetAppliedProxy():Promise<string>;

export function GetCloseToTray():Promise<boolean>;

export function GetDownloadPath(arg1:string):Promise<string>;

export function GetGeoLocation():Promise<Record<string, any>>;

export function GetProxyConfig():Promise<main.ProxyConfig>;

export function GetStartupEnabled():Promise<boolean>;

export function GetToastData():Promise<Record<string, any>>;

export function GetToastPosition():Promise<string>;

export function HideCallNotif():Promise<boolean>;

export function IsWindowFocused():Promise<boolean>;

export function MinimizeToTray():Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<boolean>;

export function PlayNotificationSound():Promise<boolean>;

export function RestartApp():Promise<boolean>;

export function RestoreNormalWindow():Promise<boolean>;

export function SaveFileFromURL(arg1:string,arg2:string):Promise<string>;

export function SaveProxyConfig(arg1:main.ProxyConfig):Promise<boolean>;

export function SetCloseToTray(arg1:boolean):Promise<boolean>;

export function SetStartupEnabled(arg1:boolean):Promise<boolean>;

export function SetToastPosition(arg1:string):Promise<boolean>;

export function ShowCallNotif(arg1:string):Promise<boolean>;

export function ShowCustomToast(arg1:string,arg2:string):Promise<boolean>;

export function ShowInExplorer(arg1:string):Promise<boolean>;

export function ShowOSNotification(arg1:string,arg2:string):Promise<boolean>;

export function ShowWindow():Promise<void>;
